### ISSUE TITLE
Log output

### ISSUE THREAD

**Issue by fascox** [xairline/xa-autoortho#1]
It is possible to redirect in a window the python output from autoortho_fuse? if is not too difficult to implement with some examples i could collaborate to this repo.

**Comment by fascox** [comment]
tail -f <logfile> work anyway 

Need a terminal window and a process open tought

**Comment by zodiac1214** [comment]
let me ask a question first. are you looking for autoortho_fuse's log or you want logs in console? if you are just looking for logs, `~/.autoortho-data/logs`. you will find it

**Comment by fascox** [comment]
As mentioned in the previous comment, a terminal window is sufficient to view the logs in real-time. Initially, the idea was to display the output directly in the console or in the main window of the UI.

**Comment by zodiac1214** [comment]
@fascox I just noticed this was first asked couple of months ago 😅 so I did a major change. If you need real time log from autoortho_fuse, you can just use terminal to tail the log file. 

Or…I get your idea wrong here?

**Comment by fascox** [comment]
no problem, you can close the issue.
